services:

  redis:
    image: redis/redis-stack:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - redis-data:/data
    ports:
      - "8001:8001"

  app:
    build: .
    image: gpt
    depends_on:
      - redis
    tty: true
    stdin_open: true
    env_file: .env
    volumes:
      - ./out:/gpt/out
    command: python -m src

  test:
    build: .
    image: gpt
    depends_on:
      - redis
    tty: true
    stdin_open: true
    env_file: .env
    command: pytest -n auto

volumes:
  redis-data:
