services:

  redis:
    image: redis:8-alpine
    command: ["redis-server", "--save", "", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  app:
    build: .
    image: gpt
    depends_on:
      - redis
    tty: true
    stdin_open: true
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379/0
    command: python -m src
    volumes:
      - ./out:/gpt/out
    ports:
      - "8000:8000"
